name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docs-check:
    name: Documentation Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Markdown Files
        run: find . -name "*.md"

    
  python-check:
    name: Python Validation
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r projects/company-server/web-app/requirements.txt

      - name: Compile Python
        run: python -m py_compile projects/company-server/web-app/app.py


  docker-check:
    name: Docker Compose Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Validate Compose File
        run: docker compose -f projects/company-server/web-app/compose.yaml config





