name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.12"

jobs:

  # Validate repository documentation
  docs-check:
    name: Documentation Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Markdown Files
        run: find . -name "*.md"

  # Validate the Flask application
  python-check:
    name: Python Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Display information about the GitHub-hosted runner
      - name: Runner Information
        run: |
          echo "Runner Name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Architecture: $RUNNER_ARCH"

      - name: System Information
        run: |
          uname -a
          docker --version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "pip"
          cache-dependency-path: projects/company-server/web-app/requirements.txt

      - name: Verify Python Version
        run: python --version

      - name: Install Dependencies
        run: pip install -r projects/company-server/web-app/requirements.txt

      - name: Compile Python
        run: python -m py_compile projects/company-server/web-app/app.py

      - name: Create Build Report
        run: |
          echo "Python validation completed successfully." > build-report.txt
          echo "Workflow: $GITHUB_WORKFLOW" >> build-report.txt
          echo "Repository:: $GITHUB_REPOSITORY" >> build-report.txt
          echo "Branch: $GITHUB_REF" >> build-report.txt
          echo "Commit: $GITHUB_SHA" >> build-report.txt
          echo "Actor: $GITHUB_ACTOR" >> build-report.txt
          echo "Run Number: $GITHUB_RUN_NUMBER" >> build-report.txt
          echo "Runner OS: $RUNNER_OS" >> build-report.txt
          echo "Python Version: ${{env.PYTHON_VERSION}}" >> build-report.txt

      - name: Upload Build Report
        uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: build-report.txt

  # Validate Docker Compose only after Python passes
  docker-check:
    name: Docker Compose Validation
    needs: python-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Compose File
        run: docker compose -f projects/company-server/web-app/compose.yaml config